### ISSUE TITLE
Very nice docker images (x11vnc & octave desktop)

### ISSUE THREAD

**Issue by git5001** [x11vnc/x11vnc-desktop#10]
I like your docker images.

One small bug in this image. With latest software update python 2.7 you need
https://bootstrap.pypa.io/pip/2.7/get-pip.py instead of https://bootstrap.pypa.io/get-pip.py

Btw. your images work basically without changes also with **Ubuntu 20.04**

**Comment by xmjiao** [comment]
Thanks for the bug report! I have incorporated the fix in the master branch and will also update the master branch to 20.04.
