### ISSUE TITLE
Easy get crash chrome , firefox browser

### ISSUE THREAD

**Issue by vd10** [x11vnc/x11vnc-desktop#4]
Hi all 
when i try using browser on x11vnc-desktop . I see it easy to crash
reproduce bug :  open several tab , quick scroll mouse up then down serveral time  or press page up/ page down several time 

**google-chrome-stable**
[2712:2823:0817/200238.637506:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[2751:2751:0817/200238.758995:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
[2712:2712:0817/200238.772510:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.

(google-chrome-stable:2712): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Unknown or unsupported transport \u201cdisabled\u201d for address \u201cdisabled:\u201d
[2712:2712:0817/200248.055402:ERROR:CONSOLE(1)] "Not allowed to load local resource: chrome-search://local-ntp/theme.css", source: https://www.google.com/_/chrome/newtab?ie=UTF-8 (1)
[1:14:0817/200256.685075:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: open context failed"}
[1:1:0817/200256.718458:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_COULD_NOT_OPEN
[1:18:0817/200257.100358:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
[1:17:0817/200324.370884:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
zsh: bus error  google-chrome-stable

**firefox** 

(/usr/lib/firefox/firefox:765): dconf-WARNING **: Unable to open /var/lib/menu-xdg/dconf/profile/user: Permission denied

(/usr/lib/firefox/firefox:725): dconf-WARNING **: Unable to open /var/lib/menu-xdg/dconf/profile/user: Permission denied
[Parent 641, Gecko_IOThread] WARNING: pipe error (47): Connection reset by peer: file /build/firefox-x_t4I3/firefox-61.0.1+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 641, Gecko_IOThread] WARNING: pipe error (56): Connection reset by peer: file /build/firefox-x_t4I3/firefox-61.0.1+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 641, Gecko_IOThread] WARNING: pipe error (55): Connection reset by peer: file /build/firefox-x_t4I3/firefox-61.0.1+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x16007F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

Does need patch chrome / firefox before to work fine on docker environment ?
Thanks you

**Comment by xmjiao** [comment]
Are you using the latest script ubuntu_desktop.py to launch the Docker image?

It is important that the "docker run" command is started with the arguments "--shm-size 2g". 
https://github.com/x11vnc/x11vnc-desktop/blob/master/ubuntu_desktop.py#L373

By default, Docker assigns only 64m to /dev/shm, which is too small and causes firefox or chrome to crash.

**Comment by vd10** [comment]
I will try it . 
Thanks for your support
