### ISSUE TITLE
Commit change on docker but lost after run again

### ISSUE THREAD

**Issue by vd10** [x11vnc/x11vnc-desktop#5]
Step to repocedure 
1.  run docker image 
2. remote vnc to runnint container
3. make some change , for example i change background desktop 
4. execute commit command of docker with new tag (example v1 )
5. close container running
6.  run docker image with new tag (v1 )
==> it lost preview change at step 3

**Comment by vd10** [comment]
@xmjiao 
Do you have any suggestion ?

**Comment by xmjiao** [comment]
Sorry for the late reply. I don't check this page regularly.

Please try to use the "-V" or "--verbose" option of the Python script:
./ubuntu_desktop.py --V

to see the options used launch docker properly. 

The configurations are saved into a persistent Docker data volume, with the volume name 
'ubuntu_' + args.tag + '_config'. If you use the same tag, it will reuse the modified config. If you commit to a different tag, then it won't be using the same config data volume.
