### ISSUE TITLE
allow pass-in VNCPASS through environment variable

### ISSUE THREAD

**Issue by wjzhou** [x11vnc/x11vnc-desktop#6]
For me, I shared my docker with a friend. Which I want to have a stable password instead of a random password every time.

I think the following change is sufficient for my need.

https://github.com/x11vnc/x11vnc-desktop/blob/e9e841cb6a34a2415d18e2a8e0be861d0e0a49fd/image/usr/local/bin/startvnc.sh#L98
```
export VNCPASS=${VNCPASS:-$(openssl rand -base64 6 | sed 's/\//-/')}
```

**Comment by xmjiao** [comment]
That is a good idea. I have incorporated the change. Thanks!
