### ISSUE TITLE
Error 1011 in NoVNC after setting resolution in LXDE

### ISSUE THREAD

**Issue by karltach** [x11vnc/x11vnc-desktop#7]
After changing the resolution in LXDE the VNC client crashes and it now longer lets you use NoVNC unless you use the `-s` flag to set resolution.  I am a bit of a Docker noob so sorry if I miss any crucial information. I am not sure where to find the logs.

When trying to connect in NoVNC, I get error 1011 in the console:

```
Failed when connecting: Connection closed (code: 1011, reason: Failed to connect to downstream server) 

rfb.js:683:21
    _fail http://45.79.46.44:6080/core/rfb.js:683
    RFB http://45.79.46.44:6080/core/rfb.js:219
    onclose http://45.79.46.44:6080/core/websock.js:224
```

**Steps to reproduce:** Start menu > Preferences > Monitor settings, then set resolution
**Server:** Ubuntu 18.04 Linode VPS, 2 cores dedicated CPU, Docker version 19.03.8, build afacb8b7f0. I run the commands within tmux.
**Modifications:** Dockerfile has apt instructions added to install extra software. Build worked after changes last night. Build command succeeds still.

edit: Workaround gets it running again, but without the `-s 1280x720` flag error persists.

**Comment by blindstitch** [comment]
Software installed was obs-studio, ffmpeg, vlc, youtube-dl, and pulseaudio.

**Comment by xmjiao** [comment]
Sorry for not following up with this issue. It was probably because the resolution 1280x720 was not supported. The supported modes are listed on this line:
https://github.com/x11vnc/x11vnc-desktop/blob/master/image/etc/X11/xorg.conf#L124
I just edited the file by adding the mode 1280x720.
